// prisma/seed-countries.ts - Заполнение базы странами и тарифами доставки
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  { name: 'Беларусь', code: 'BY', price: 0, isActive: true, order: 0 },
  { name: 'Австралия', code: 'AU', price: 150, isActive: true, order: 1 },
  { name: 'Австрия', code: 'AT', price: 100, isActive: true, order: 1 },
  { name: 'Азербайджан', code: 'AZ', price: 90, isActive: true, order: 1 },
  { name: 'Албания', code: 'AL', price: 110, isActive: true, order: 1 },
  { name: 'Алжир', code: 'DZ', price: 110, isActive: true, order: 1 },
  { name: 'Ангола', code: 'AO', price: 140, isActive: true, order: 1 },
  { name: 'Андорра', code: 'AD', price: 110, isActive: true, order: 1 },
  { name: 'Аргентина', code: 'AR', price: 140, isActive: true, order: 1 },
  { name: 'Армения', code: 'AM', price: 100, isActive: true, order: 1 },
  { name: 'Афганистан', code: 'AF', price: 130, isActive: true, order: 1 },
  { name: 'Бангладеш', code: 'BD', price: 130, isActive: true, order: 1 },
  { name: 'Бахрейн', code: 'BH', price: 130, isActive: true, order: 1 },
  { name: 'Бельгия', code: 'BE', price: 120, isActive: true, order: 1 },
  { name: 'Болгария', code: 'BG', price: 90, isActive: true, order: 1 },
  { name: 'Боливия', code: 'BO', price: 170, isActive: true, order: 1 },
  { name: 'Босния и Герцеговина', code: 'BA', price: 110, isActive: true, order: 1 },
  { name: 'Бразилия', code: 'BR', price: 150, isActive: true, order: 1 },
  { name: 'Бруней', code: 'BN', price: 140, isActive: true, order: 1 },
  { name: 'Великобритания', code: 'GB', price: 140, isActive: true, order: 1 },
  { name: 'Венгрия', code: 'HU', price: 110, isActive: true, order: 1 },
  { name: 'Венесуэла', code: 'VE', price: 160, isActive: true, order: 1 },
  { name: 'Вьетнам', code: 'VN', price: 100, isActive: true, order: 1 },
  { name: 'Германия', code: 'DE', price: 130, isActive: true, order: 1 },
  { name: 'Греция', code: 'GR', price: 100, isActive: true, order: 1 },
  { name: 'Грузия', code: 'GE', price: 110, isActive: true, order: 1 },
  { name: 'Дания', code: 'DK', price: 110, isActive: true, order: 1 },
  { name: 'Египет', code: 'EG', price: 110, isActive: true, order: 1 },
  { name: 'Израиль', code: 'IL', price: 110, isActive: true, order: 1 },
  { name: 'Индия', code: 'IN', price: 110, isActive: true, order: 1 },
  { name: 'Индонезия', code: 'ID', price: 120, isActive: true, order: 1 },
  { name: 'Иордания', code: 'JO', price: 120, isActive: true, order: 1 },
  { name: 'Ирак', code: 'IQ', price: 100, isActive: true, order: 1 },
  { name: 'Иран', code: 'IR', price: 130, isActive: true, order: 1 },
  { name: 'Ирландия', code: 'IE', price: 110, isActive: true, order: 1 },
  { name: 'Исландия', code: 'IS', price: 130, isActive: true, order: 1 },
  { name: 'Испания', code: 'ES', price: 110, isActive: true, order: 1 },
  { name: 'Италия', code: 'IT', price: 100, isActive: true, order: 1 },
  { name: 'Казахстан', code: 'KZ', price: 120, isActive: true, order: 1 },
  { name: 'Канада', code: 'CA', price: 140, isActive: true, order: 1 },
  { name: 'Катар', code: 'QA', price: 130, isActive: true, order: 1 },
  { name: 'Кипр', code: 'CY', price: 100, isActive: true, order: 1 },
  { name: 'Китай', code: 'CN', price: 100, isActive: true, order: 1 },
  { name: 'Колумбия', code: 'CO', price: 160, isActive: true, order: 1 },
  { name: 'Корея (Южная)', code: 'KR', price: 110, isActive: true, order: 1 },
  { name: 'Куба', code: 'CU', price: 140, isActive: true, order: 1 },
  { name: 'Кувейт', code: 'KW', price: 130, isActive: true, order: 1 },
  { name: 'Кыргызстан', code: 'KG', price: 80, isActive: true, order: 1 },
  { name: 'Латвия', code: 'LV', price: 80, isActive: true, order: 1 },
  { name: 'Ливан', code: 'LB', price: 110, isActive: true, order: 1 },
  { name: 'Ливия', code: 'LY', price: 110, isActive: true, order: 1 },
  { name: 'Литва', code: 'LT', price: 90, isActive: true, order: 1 },
  { name: 'Люксембург', code: 'LU', price: 100, isActive: true, order: 1 },
  { name: 'Малайзия', code: 'MY', price: 100, isActive: true, order: 1 },
  { name: 'Мальта', code: 'MT', price: 140, isActive: true, order: 1 },
  { name: 'Марокко', code: 'MA', price: 130, isActive: true, order: 1 },
  { name: 'Мексика', code: 'MX', price: 110, isActive: true, order: 1 },
  { name: 'Молдова', code: 'MD', price: 110, isActive: true, order: 1 },
  { name: 'Нигерия', code: 'NG', price: 140, isActive: true, order: 1 },
  { name: 'Нидерланды', code: 'NL', price: 100, isActive: true, order: 1 },
  { name: 'Новая Зеландия', code: 'NZ', price: 150, isActive: true, order: 1 },
  { name: 'Норвегия', code: 'NO', price: 130, isActive: true, order: 1 },
  { name: 'ОАЭ', code: 'AE', price: 80, isActive: true, order: 1 },
  { name: 'Пакистан', code: 'PK', price: 110, isActive: true, order: 1 },
  { name: 'Польша', code: 'PL', price: 100, isActive: true, order: 1 },
  { name: 'Португалия', code: 'PT', price: 110, isActive: true, order: 1 },
  { name: 'Россия', code: 'RU', price: 130, isActive: true, order: 1 },
  { name: 'Румыния', code: 'RO', price: 130, isActive: true, order: 1 },
  { name: 'Саудовская Аравия', code: 'SA', price: 130, isActive: true, order: 1 },
  { name: 'Сербия', code: 'RS', price: 110, isActive: true, order: 1 },
  { name: 'Сингапур', code: 'SG', price: 110, isActive: true, order: 1 },
  { name: 'Сирия', code: 'SY', price: null, isActive: false, order: 1 },
  { name: 'Словакия', code: 'SK', price: 90, isActive: true, order: 1 },
  { name: 'Словения', code: 'SI', price: 90, isActive: true, order: 1 },
  { name: 'США', code: 'US', price: 130, isActive: true, order: 1 },
  { name: 'Таджикистан', code: 'TJ', price: 90, isActive: true, order: 1 },
  { name: 'Таиланд', code: 'TH', price: 100, isActive: true, order: 1 },
  { name: 'Тайвань', code: 'TW', price: 140, isActive: true, order: 1 },
  { name: 'Тунис', code: 'TN', price: 130, isActive: true, order: 1 },
  { name: 'Туркменистан', code: 'TM', price: 80, isActive: true, order: 1 },
  { name: 'Турция', code: 'TR', price: 120, isActive: true, order: 1 },
  { name: 'Узбекистан', code: 'UZ', price: 130, isActive: true, order: 1 },
  { name: 'Украина', code: 'UA', price: null, isActive: false, order: 1 },
  { name: 'Филиппины', code: 'PH', price: 120, isActive: true, order: 1 },
  { name: 'Финляндия', code: 'FI', price: null, isActive: false, order: 1 },
  { name: 'Франция', code: 'FR', price: 110, isActive: true, order: 1 },
  { name: 'Хорватия', code: 'HR', price: 90, isActive: true, order: 1 },
  { name: 'Черногория', code: 'ME', price: 110, isActive: true, order: 1 },
  { name: 'Чехия', code: 'CZ', price: 90, isActive: true, order: 1 },
  { name: 'Чили', code: 'CL', price: 170, isActive: true, order: 1 },
  { name: 'Швейцария', code: 'CH', price: 100, isActive: true, order: 1 },
  { name: 'Швеция', code: 'SE', price: 120, isActive: true, order: 1 },
  { name: 'Шри-Ланка', code: 'LK', price: 110, isActive: true, order: 1 },
  { name: 'Эстония', code: 'EE', price: 100, isActive: true, order: 1 },
  { name: 'ЮАР', code: 'ZA', price: 140, isActive: true, order: 1 },
  { name: 'Япония', code: 'JP', price: 110, isActive: true, order: 1 },
];

async function seed() {
  console.log('Seeding countries...');

  for (const country of countries) {
    await prisma.country.upsert({
      where: { code: country.code },
      update: {
        price: country.price,
        isActive: country.isActive,
      },
      create: country,
    });
  }

  console.log(`Seeded ${countries.length} countries`);
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
